export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_CATEGORY_INFO_REQUEST = 'FETCH_CATEGORY_INFO_REQUEST';
export const FETCH_CATEGORY_INFO_SUCCESS = 'FETCH_CATEGORY_INFO_SUCCESS';
export const FETCH_CATEGORY_INFO_FAILURE = 'FETCH_CATEGORY_INFO_FAILURE';